M48
; DRILL file {KiCad 9.0.2} date 2026-05-12T13:54:20-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T13:54:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X89.65Y-93.825
X89.65Y-96.825
X167.0Y-38.5
X170.0Y-38.5
T2
X88.0Y-39.0
X88.0Y-126.0
X189.0Y-39.0
X189.0Y-126.0
M30
